import { Metadata } from "next";
import ImgForm from "../_component/imgform/page";
import LinkForm from "../_component/linkform/page";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="container">
          <div className="min-h-screen flex justify-center items-center gap-7">
            <ImgForm />

            <div>
              <LinkForm />
              <div>
                {children}
                <Toaster />
              </div>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
