import { Metadata } from "next";
import Navlink from "../_component/navlink/page";
import Shearch from "../_component/shearch/page";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="container">
          <div className=" flex md:flex-row mt-7">
            <div className="w-1/5 p-3">
              <Navlink />
            </div>
            <div className="w-4/5">
              <Shearch />
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
